# Change these first
owner: fbigrs # Your GitHub organization or username, where this repository lives
repo: status.fgross.cloud # The name of this repository

sites:
  - name: Thor (Main)
    check: "tcp-ping"
    url: 144.76.40.174
    port: 22

  - name: PVE01 (Main)
    check: "tcp-ping"
    url: 45.153.35.198
    port: 22
  
  - name: Game & Voice Host
    check: "tcp-ping"
    url: 45.153.35.208
    port: 22

  - name: Cloud
    check: "tcp-ping"
    url: 45.153.35.199
    port: 22

  - name: Mail Service
    check: "tcp-ping"
    url: 82.165.1.212
    port: 22

  - name: Zabbix
    check: "tcp-ping"
    url: 37.27.86.65
    port: 22

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.fgross.cloud
  # baseUrl: /your-repo-name
  logoUrl: https://i.imgur.com/qQB1q9g.png
  name: Status - fgross.cloud
  introTitle: "**Status** for fgross.cloud services."
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: night

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
